import { ApiProperty } from '@nestjs/swagger';
import { IsNotEmpty, NotEquals } from 'class-validator';

export class PartsDTO {
    constructor() {
        this.id = ""
        this.name = ""
        this.plant = 0
        this.units = 0
        this.weight = 0
    }
    @ApiProperty({ example: '65158bd8284831c98f44b798',
    description: 'Autogenerated ID' })
    id: string;

    @ApiProperty({ example: 'Part Name', description: 'Name of the part' })
    @IsNotEmpty({ message: 'Name cannot be empty' })
    name: string;

    @ApiProperty({ example: 1, description: 'Plant code' })
    @NotEquals(0, { message: 'plant should not be empty' })
    plant: number;

    @ApiProperty({ example: 10, description: 'Number of units' })
    @NotEquals(0, { message: 'units should not be empty' })
    units: number;
    
    @ApiProperty({ example: 50, description: 'Weight in grams' })
    @NotEquals(0, { message: 'weight should not be empty' })
    weight: number;
}